"""add auth and roles

Revision ID: d832b397b98d
Revises: 97e0424909f9
Create Date: 2025-10-14 12:10:52.567482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.security import hash_password
import uuid
import datetime

# revision identifiers, used by Alembic.
revision: str = "d832b397b98d"
down_revision: Union[str, Sequence[str], None] = "97e0424909f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создание ENUM типа для ролей
    user_role_enum = sa.Enum("ADMIN", "VERIFIED_AUTHOR", "USER", name="userrole")
    user_role_enum.create(op.get_bind())

    # 1. Добавление новых колонок
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("role", user_role_enum, nullable=False, server_default="USER"),
    )

    # Обновление существующих данных: is_verified_author -> role
    op.execute(
        "UPDATE users SET role = 'VERIFIED_AUTHOR' WHERE is_verified_author = TRUE"
    )
    op.execute(
        "UPDATE users SET hashed_password = '{}'".format(
            hash_password("dummy_password")
        )
    )

    # 2. Удаление старой колонки
    op.drop_column("users", "is_verified_author")

    # 3. Создание таблицы refresh_tokens
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_refresh_token"),
        "refresh_tokens",
        ["refresh_token"],
        unique=True,
    )

    # 4. Обновление внешних ключей для каскадного удаления
    op.drop_constraint("news_author_id_fkey", "news", type_="foreignkey")
    op.create_foreign_key(
        "news_author_id_fkey",
        "news",
        "users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint("comments_author_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_author_id_fkey",
        "comments",
        "users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint("comments_news_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_news_id_fkey",
        "comments",
        "news",
        ["news_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # 5. Добавление админа
    users_table = sa.table(
        "users",
        sa.column("id", sa.UUID),
        sa.column("name", sa.String),
        sa.column("email", sa.String),
        sa.column("hashed_password", sa.String),
        sa.column("role", sa.String),
        sa.column("registered_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        users_table,
        [
            {
                "id": uuid.uuid4(),
                "name": "Admin User",
                "email": "admin@example.com",
                "hashed_password": hash_password("admin_password"),
                "role": "ADMIN",
                "registered_at": datetime.datetime.now(datetime.timezone.utc),
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email = 'admin@example.com'")

    op.drop_constraint("comments_news_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_news_id_fkey", "comments", "news", ["news_id"], ["id"]
    )

    op.drop_constraint("comments_author_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_author_id_fkey", "comments", "users", ["author_id"], ["id"]
    )

    op.drop_constraint("news_author_id_fkey", "news", type_="foreignkey")
    op.create_foreign_key("news_author_id_fkey", "news", "users", ["author_id"], ["id"])

    op.drop_index(op.f("ix_refresh_tokens_refresh_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")

    op.add_column(
        "users",
        sa.Column(
            "is_verified_author",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.execute(
        "UPDATE users SET is_verified_author = TRUE WHERE role = 'VERIFIED_AUTHOR'"
    )

    op.drop_column("users", "role")
    op.drop_column("users", "hashed_password")

    sa.Enum(name="userrole").drop(op.get_bind())
    # ### end Alembic commands ###
